#-----------------------------------------------------------------------------
# Title   : Padframe Configuration File
# -----------------------------------------------------------------------------
# File    : padframe_config_generic.yml
# Author  : Manuel Eggimann <meggimann@iis.ee.ethz.ch>
# Created : 04.12.2022
# -----------------------------------------------------------------------------
# Description :
#
# This file descibes the padframe and IO multiplexing strategy of PULPissimo.
# The file is parsed by a CLI tool called padrick that auto-generates the IO
# multiplexing and pad instantation IP automatically. This files is intended to
# be used with the generic IO pad models from the pulp tech_cells_generic
# repository. You can use this file as a template to create a tape-out specific
# config file for your target technology.
#
# You can find more information about the syntax of this file on
# https://padrick.readthedocs.io/en/latest/
#
#-----------------------------------------------------------------------------
# Copyright (C) 2022 ETH Zurich, University of Bologna Copyright and related
# rights are licensed under the Solderpad Hardware License, Version 0.51 (the
# "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law or
# agreed to in writing, software, hardware and materials distributed under this
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
# SPDX-License-Identifier: SHL-0.51
# -----------------------------------------------------------------------------

manifest_version: 3
name: pulpissimo_padframe
user_attr:
  target_platform: fpga
  num_gpios: !include gpio_count.txt
pad_domains:
  - name: all_pads
    pad_types:
      !include fpga_config/fpga_pad_types.yml

    pad_list:
      !include fpga_config/fpga_pads.yml

    port_groups:
      !include common_peripherals.yml

